[package]
name = "teajey-accord"
version = "0.1.0"
edition = "2021"
description = "Generate Typescript according to a GraphQL schema."
license = "MIT"
repository = "https://github.com/Teajey/accord"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug = ["lazy_static"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
console = "0.15.5"
convert_case = "0.6.0"
eyre = "0.6.8"
graphql-parser = "0.4.0"
graphql_client = "0.11.0"
lazy_static = { version = "1.4.0", optional = true }
macros = { version = "0.1.0", path = "../macros" }
regex = "1.7.0"
regex-macro = "0.2.0"
serde = { version = "1.0.145", features = ["derive"] }
serde-wasm-bindgen = "0.4.5"
serde_json = "1.0.86"
serde_yaml = "0.9.14"
url = { version = "2.3.1", features = ["serde"] }

[dev-dependencies]
insta = "1.21.0"
pretty_assertions = "1.3.0"

[target.'cfg(not(any(target_arch = "wasm32", target_arch = "wasm64")))'.dependencies]
reqwest = { version = "0.11.12", features = ["json"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
glob = "0.3.1"

[target.'cfg(any(target_arch = "wasm32", target_arch = "wasm64"))'.dependencies]
wasm-bindgen = { version = "0.2.83" }
wasm-bindgen-futures = { version = "0.4.33" }
js-sys = { version = "0.3.60" }
