generates:
  mySchema:
    schema:
      url: "{{GRAFT_DOMAIN}}"
      noSsl: true
      out:
        ast: schema.graphql
        json: schema.json
    typescript:
      ast: schema.graphql
      documents: document.graphql
      out: generated.ts
