name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: /cargo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache
      uses: actions/cache@v3.2.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: /cargo
        # An explicit key for restoring and saving the cache
        key: graft-cargo-cache
        # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
#         restore-keys: # optional
        # The chunk size used to split up large files during upload, in bytes
#         upload-chunk-size: # optional
        # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
#         enableCrossOsArchive: # optional, default is false
        # Fail the workflow if cache entry is not found
#         fail-on-cache-miss: true
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
